.TH owl 8 owl\-git
.SH NAME
owl \- Pacman and cower wrapper focused on simplicity
.SH SYNOPSIS
.BI owl\ ACTION
.RI [ OPTIONS ]
.RI [ ARGUMENTS ]
.SH DESCRIPTION
owl is a simple wrapper for pacman and cower, providing seamless access to all the available Arch Linux packages.
.SH ACTIONS
.TP
.B refresh
Update package list.
.TP
.B update
Update package list and upgrade all packages afterwards.
.TP
.B pull
Grab changes for all the cached AUR packages.
.TP
.BI "install " "PKG " ...
Install the given packages.
.TP
.BI "upgrade " "PKG " ...
Upgrade the given packages.
.TP
.BI "downgrade " "PKG " ...
Downgrade the given packages.
.TP
.B remove
.TQ
.BI "uninstall " "PKG " ...
Remove the given packages.
.TP
.BI "download " "PKG " ...
Download the given packages from the AUR.
.TP
.BI "abs " "PKG " ...
Download the given sync packages via abs.
.TP
.BI "edit " PKG
Edit the PKGBUILD for the given AUR package.
.TP
.BI "search " STRING
Search for packages matching
.I STRING
in all databases.
.TP
.BI "query " STRING
Search locally for packages matching
.IR STRING .
.TP
.BI "info " "PKG " ...
Retrieve informations on the given packages.
.TP
.BI "deps " "PKG " ...
Show dependencies for the given packages.
.TP
.BI "mdeps " "PKG " ...
Show make dependencies for the given packages.
.TP
.BI "uses " "PKG " ...
Show packages that specify the given packages as dependency.
.TP
.BI "owns " FILE
Return the name of the package owning the given file.
.TP
.BI "version " "PKG " ...
Return the version of the given packages.
.TP
.BI "repository " "PKG " ...
Return the repository of the given packages.
.TP
.BI "description " "PKG " ...
Return the description of the given packages.
.TP
.BI "category " "PKG " ...
Return the category of the given AUR packages.
.TP
.BI "license " "PKG " ...
Return the license of the given packages.
.TP
.BI "page " "PKG " ...
Opens the given packages AUR pages.
.TP
.BI "home " "PKG " ...
Opens the given packages home pages.
.TP
.BI "changelog " "PKG " ...
Opens the given packages *changelog* pages.
.TP
.BI "list " "PKG " ...
List all the files owned by the given packages.
.TP
.BI "lsgrep " "STRING PKG " ...
Restrict the output of 'list' to packages matching STRING.
.TP
.BI "binlist " "PKG " ...
Restrict the output of
.B list
to executable files.
.TP
.BI "liblist " "PKG " ...
Restrict the output of
.B list
to library files.
.TP
.BI "etclist " "PKG " ...
Restrict the output of
.B list
to configuration files.
.TP
.BI "manlist " "PKG " ...
Restrict the output of
.B list
to manual files.
.TP
.BI "doclist " "PKG " ...
Restrict the output of
.B list
to documentation files.
.TP
.BI "grep " "STRING PKG " ...
Grep for
.I STRING
in all the files of all the given packages.
.TP
.BI "check " "PKG " ...
Check that all files owned by the given packages exist.
.TP
.B prune
Remove unused repositories in the cache directory.
.TP
.BI "last " [NUM]
Show the last
.I NUM
(7 if omitted) installed packages.
.TP
.B leftovers
Find, merge and remove
.I pac{new,orig,save}
files.
.TP
.B foreigns
Show installed packages not found in the sync databases.
.TP
.B orphans
Show packages not listed as a dependency by any package.
.SH OPTIONS
The actions on which each option applies are given between parenthesis.
.TP
.BR -q ,\  --quiet "  (search, query, foreigns, orphans, owns, changelog)"
Provide quiet search results.
.TP
.BR -e ,\  --extended "  (info)"
Provide extended informations.
.TP
.BR -a ,\  --aur "  (update, search)"
Restrain the action to the AUR packages.
.TP
.BR -o ,\  --repo "  (update, search)"
Restrain the action to the sync packages.
.TP
.BR -l ,\  --local "  (info, deps, uses, version, repository, category, description)"
Restrain the action to the local packages.
.TP
.BR -i ,\  --ignore-outdated "  (search)"
Exclude outdated AUR packages from search results.
.TP
.BR -s ,\  --recursive "  (remove, uninstall)"
See pacman's remove options.
.TP
.BR -c ,\  --cascade "  (remove, uninstall)"
See pacman's remove options.
.TP
.BR -d ,\  --dependencies "  (download)"
Fetch dependencies.
.TP
.BR -w ,\  --crawl-homes "  (home)"
Open every pages of all the packages matching the argument.
.SH CONFIGURATION
The following environment variables are used:
.IP \[bu] 2
.I OWL_AUR_HOME
-- where should the downloaded AUR packages be stored?
.IP \[bu]
.I OWL_ABS_HOME
-- where should the downloaded sync packages be stored?
.IP \[bu]
.I OWL_CHANGELOG_DB
-- path to the database of changelog URLs.
.IP \[bu]
.I OWL_ABS_ROOT
-- the value of the ABSROOT variable in /etc/abs.conf.
.IP \[bu]
.I OWL_PACMAN_CACHE
-- the value of the CacheDir variable in /etc/pacman.conf.
.IP \[bu]
.I OWL_PACMAN_LOG
-- the value of the LogFile variable in /etc/pacman.conf.
.IP \[bu]
.I OWL_BROWSER
-- the browser used for opening the packages home pages.
.IP \[bu]
.I OWL_EDITOR
-- the editor used for opening the package's PKGBUILDs.
.IP \[bu]
.I OWL_SUDO_WARN
-- print a warning each time sudo is run (default: true).
.IP \[bu]
.I OWL_COLORIZE_RESULTS
-- colorize search results (default: true).
.IP \[bu]
.I OWL_IGNORE_OUTDATED
-- whether to ignore outdated AUR results (default: false).
.IP \[bu]
.I OWL_CLEAN_UP
-- whether to pass the
.B -c
flag to
.BR makepkg (8).
.IP \[bu]
.I OWL_MAX_URL
-- the maximum number of URL to send at once via
.BR --crawl-homes .
.P
.SS Color Variables
.IP \[bu] 2
.I OWL_LOCAL_COLOR
.IP \[bu]
.I OWL_CORE_COLOR
.IP \[bu]
.I OWL_EXTRA_COLOR
.IP \[bu]
.I OWL_COMMUNITY_COLOR
.IP \[bu]
.I OWL_TESTING_COLOR
.IP \[bu]
.I OWL_AUR_COLOR
.IP \[bu]
.I OWL_OTHER_COLOR
.IP \[bu]
.I OWL_SEP_COLOR
.IP \[bu]
.I OWL_NAME_COLOR
.IP \[bu]
.I OWL_VERSION_COLOR
.IP \[bu]
.I OWL_OBSOLETE_COLOR
.IP \[bu]
.I OWL_INSTALLED_COLOR
.P
The valid values for the aforementioned variables are:

.IR default ,\  black ,\  red ,\  green ,\  yellow ,\  blue ,\  magenta ,\  cyan ,\  white ,\  bold .
.SH AUTHOR
.MT baskerville@lavabit.com
Bastien Dejean
.ME
.SH LINKS
.UR https://github.com/baskerville/owl
Homepage
.UE
.SH SEE ALSO
.BR pacman (8),
.BR makepkg (8),
.BR cower (1)
