.TH owl 8 owl\-git
.SH NAME
owl \- Pacman and cower wrapper focused on simplicity
.SH SYNOPSIS
.BI owl\ ACTION
.RI [ OPTIONS ]
.RI [ ARGUMENTS ]
.SH DESCRIPTION
owl is a simple wrapper for pacman and cower, providing seamless access to all the available Arch Linux packages.
.P
It is inspired by homebrew.
.SH ACTIONS
.TP
.B update
Update package list and upgrade all packages afterwards.
.TP
.B pull
Grab changes for all the cached AUR packages.
.TP
.BI "install " "PKG " ...
Install the given packages.
.TP
.BI "remove " "PKG " ...
Remove the given packages.
.TP
.BI "download " "PKG " ...
Download the given packages from the AUR.
.TP
.BI "search " STRING
Search for packages matching
.I STRING
in all databases.
.TP
.BI "query " STRING
Search locally for packages matching
.IR STRING .
.TP
.BI "info " "PKG " ...
Retreive informations on the given packages.
.TP
.BI "deps " "PKG " ...
Show dependencies for the given packages.
.TP
.BI "uses " "PKG " ...
Show packages that specify the given packages as dependency.
.TP
.BI "owns " FILE
Return the name of the package owning the given file.
.TP
.BI "version " "PKG " ...
Return the version of the given packages.
.TP
.BI "repository " "PKG " ...
Return the repository of the given packages.
.TP
.BI "description " "PKG " ...
Return the description of the given packages.
.TP
.BI "category " "PKG " ...
Return the category of the given AUR packages.
.TP
.BI "page " "PKG " ...
Opens the given packages AUR pages.
.TP
.BI "home " "PKG " ...
Opens the given packages home pages.
.TP
.BI "list " "PKG " ...
List all the files owned by the given packages.
.TP
.BI "lsgrep " "STRING PKG " ...
Restrict the output of 'list' to packages matching STRING.
.TP
.BI "binlist " "PKG " ...
Restrict the output of
.B list
to executable files.
.TP
.BI "etclist " "PKG " ...
Restrict the output of
.B list
to configuration files.
.TP
.BI "manlist " "PKG " ...
Restrict the output of
.B list
to manual files.
.TP
.BI "doclist " "PKG " ...
Restrict the output of
.B list
to documentation files.
.TP
.BI "grep " "STRING PKG " ...
Grep for
.I STRING
in all the files of all the given packages.
.TP
.B cleanup
Remove unused repositories in the cache directory.
.TP
.B leftovers
Search and propose merges for
.I pac{new,orig,save}
files.
.TP
.B foreigns
Show installed packages not found in the sync databases.
.TP
.B orphans
Show packages not listed as a dependency by any package.
.SH OPTIONS
The actions on which the options applies are given between parenthesis.
.TP
.BR -q ,\  --quiet "  (search, query, foreigns, orphans)"
Provide quiet search results.
.TP
.BR -a ,\  --aur "  (update, search)"
Retrain the action to the AUR packages.
.TP
.BR -o ,\  --repo "  (search)"
Restrain the action to the sync packages.
.TP
.BR -l ,\  --local "  (info)"
Restrain the action to the local packages.
.TP
.BR -i ,\  --ignore-outdated "  (search)"
Exclude outdated AUR packages from search results.
.TP
.BR -s ,\  --recursive "  (remove)"
See pacman's remove options.
.TP
.BR -c ,\  --cascade "  (remove)"
See pacman's remove options.
.TP
.BR -d ,\  --dependencies "  (download)"
Fetch dependencies.
.TP
.BR -w ,\  --crawl-homes "  (home)"
Open every pages of all the packages matching the argument.
.SH CONFIGURATION
The following environment variables are used:
.IP \[bu] 2
.I XDG_AUR_HOME
-- where should the downloaded AUR packages be stored?
.IP \[bu]
.I BROWSER
-- the browser used for opening the packages home pages.
.IP \[bu]
.I OWL_SUDO_WARN
-- print a warning each time sudo is run (default value: 'true').
.IP \[bu]
.I OWL_COLOR_RESULTS
-- colorize search results (default value: 'true').
.IP \[bu]
.I OWL_IGNORE_OUTDATED
-- whether to ignore outdated AUR results (default value: 'false').
.IP \[bu]
.I OWL_MAX_URL
-- the maximum number of URL this program is allowed to send to the
.I BROWSER
in one go.
.P
Color related variables (self-explained):
.IP \[bu] 2
.I OWL_LOCAL_COLOR
.IP \[bu]
.I OWL_CORE_COLOR
.IP \[bu]
.I OWL_EXTRA_COLOR
.IP \[bu]
.I OWL_COMMUNITY_COLOR
.IP \[bu]
.I OWL_TESTING_COLOR
.IP \[bu]
.I OWL_AUR_COLOR
.IP \[bu]
.I OWL_SEP_COLOR
.IP \[bu]
.I OWL_NAME_COLOR
.IP \[bu]
.I OWL_VERSION_COLOR
.IP \[bu]
.I OWL_OBSOLETE_COLOR
.IP \[bu]
.I OWL_INSTALLED_COLOR
.P
The valid values for the aforementioned variables are:

.IR black ,\  red ,\  green ,\  yellow ,\  blue ,\  magenta ,\  cyan ,\  white ,\  bold .
.SH AUTHOR
.EX
Bastien Dejean <baskerville a lavabit o com>
.EE
.SH HOMEPAGE
.TP
https://github.com/baskerville/owl
.SH SEE ALSO
.BR pacman (8),
.BR makepkg (8),
.BR cower (1)
