.TH owl 8 owl\-git
.SH NAME
owl \- Pacman and cower wrapper focused on simplicity
.SH SYNOPSIS
.BI owl\ ACTION
.RI [ OPTIONS ]
.RI [ ARGUMENTS ]
.SH DESCRIPTION
owl is a simple wrapper for pacman and cower, providing seamless access to all the available Arch Linux packages.
.P
It is inspired by homebrew.
.SH ACTIONS
.TP
.B update
Update package list and upgrade all packages afterwards.
.TP
.B pull
Grab changes for all the cached AUR packages.
.TP
.BI "install " "PKG " ...
Install the given packages.
.TP
.BI "remove " "PKG " ...
Remove the given packages.
.TP
.BI "download " "PKG " ...
Download the given packages from the AUR.
.TP
.BI "view " "PKG " ...
Retreive informations on the given packages.
.TP
.BI "page " "PKG " ...
Opens the given packages AUR pages.
.TP
.BI "home " "PKG " ...
Opens the given packages home pages.
.TP
.BI "find " STRING
Search for packages matching
.I STRING
in the sync databases.
.TP
.BI "search " STRING
Search for packages matching
.I STRING
in the AUR.
.TP
.BI "query " STRING
Search locally for packages matching
.IR STRING .
.TP
.BI "list " "PKG " ...
List all the files owned by the given packages.
.TP
.BI "listgrep " "STRING PKG " ...
Restrict the output of 'list' to packages matching STRING.
.TP
.BI "listbin " "PKG " ...
Restrict the output of
.B list
to executable files.
.TP
.BI "listetc " "PKG " ...
Restrict the output of
.B list
to configuration files.
.TP
.BI "listman " "PKG " ...
Restrict the output of
.B list
to manual files.
.TP
.BI "grep " "STRING PKG " ...
Search for
.I STRING
in all the files belonging to the given packages.
.TP
.BI "owner " FILE
Return the name of the package owning the given file.
.TP
.B cleanup
Remove unused repositories in the cache directory.
.TP
.B leftovers
Search and propose merges for
.I pac{new,orig,save}
files.
.TP
.B foreigns
Show installed packages not found in the sync databases.
.TP
.B orphans
Show packages not listed as a dependency by any package.
.SH OPTIONS
.TP
.BR -a ,\ --aur
Only update AUR packages.
.TP
.BR -s ,\ --recursive
See pacman's remove options.
.TP
.BR -c ,\ --cascade
See pacman's remove options.
.TP
.BR -q ,\ --quiet
Provide quiet search results.
.TP
.BR -d ,\ --dependencies
Fetch dependencies.
.TP
.BR -h ,\ --crawl-homes
Open every pages of all the packages matching the argument.
.SH CONFIGURATION
The following environment variables are used:
.IP \[bu] 2
.B XDG_AUR_HOME
-- where should the downloaded AUR packages be stored?
.IP \[bu]
.B BROWSER
-- the browser used for opening the packages home pages.
.IP \[bu]
.B OWL_SUDO_WARN
-- print a warning each time sudo is run (default value: 'true').
.IP \[bu]
.B OWL_COLOR_RESULTS
-- colorize search results (default value: 'true').
.IP \[bu]
.B OWL_MAX_URL
-- the maximum number of URL this program is allowed to send to the
.B BROWSER
in one go.
.P
Color related variables (self-explained):
.IP \[bu] 2
.B OWL_LOCAL_COLOR
.IP \[bu]
.B OWL_CORE_COLOR
.IP \[bu]
.B OWL_EXTRA_COLOR
.IP \[bu]
.B OWL_COMMUNITY_COLOR
.IP \[bu]
.B OWL_TESTING_COLOR
.IP \[bu]
.B OWL_AUR_COLOR
.IP \[bu]
.B OWL_SEP_COLOR
.IP \[bu]
.B OWL_NAME_COLOR
.IP \[bu]
.B OWL_VERSION_COLOR
.IP \[bu]
.B OWL_OBSOLETE_COLOR
.IP \[bu]
.B OWL_INSTALLED_COLOR
.P
The valid values for the aforementioned variables are:

.IR black ,\  red ,\  green ,\  yellow ,\  blue ,\  magenta ,\  cyan ,\  white ,\  bold .
.SH AUTHOR
.EX
Bastien Dejean <baskerville a lavabit o com>
.EE
.SH HOMEPAGE
.TP
https://github.com/baskerville/owl
.SH SEE ALSO
.BR pacman (8),
.BR makepkg (8),
.BR cower (1)
